export const MARK_PATH = 'M 5,60 L 5,35 A 25,25 0 0,1 55,35 L 55,60 L 44,60 L 44,35 A 14,14 0 0,0 16,35 L 16,60 Z';

export const CAT_LABELS: Record<string, string> = {
  market: 'MARKET INSIGHTS',
  living: 'LUXURY LIVING',
  neighbourhood: 'NEIGHBOURHOODS',
  investment: 'INVESTMENT',
  news: 'NEWS',
};

export const STATIC_ARTICLES = [
  {
    _id: '1',
    slug: 'waterfront-living-lagos',
    category: 'market',
    title: 'The Rise of Waterfront Living in Lagos: Why Ikoyi & Victoria Island Command Premium Prices',
    excerpt: "Nigeria's coastal luxury market has undergone a profound transformation over the past decade. We examine the forces reshaping premium waterfront real estate in Lagos — and what it means for buyers and investors alike.",
    publishedAt: '2026-05-28T00:00:00Z',
    readTime: '8 min',
    author: 'Amara Obi',
    authorRole: 'Senior Property Advisor',
    authorBio: '12 years advising ultra-high-net-worth clients on luxury acquisitions across Lagos and Abuja.',
    featured: true,
    tags: ['Lagos', 'Ikoyi', 'Victoria Island', 'Waterfront', 'Investment'],
    coverImageUrl: null,
    body: null,
  },
  {
    _id: '2',
    slug: 'investment-outlook-2026',
    category: 'investment',
    title: '2026 Outlook: Where Smart Money Is Moving in Nigerian Real Estate',
    excerpt: "A detailed analysis of emerging investment corridors, yield expectations, and the macro trends shaping portfolio decisions for Nigeria's high-net-worth investors.",
    publishedAt: '2026-05-22T00:00:00Z',
    readTime: '6 min',
    author: 'Amara Obi',
    authorRole: 'Senior Property Advisor',
    authorBio: '12 years advising ultra-high-net-worth clients on luxury acquisitions across Lagos and Abuja.',
    featured: false,
    tags: ['Investment', 'Nigeria', 'Portfolio'],
    coverImageUrl: null,
    body: null,
  },
  {
    _id: '3',
    slug: 'banana-island-guide',
    category: 'neighbourhood',
    title: "Banana Island: Understanding Africa's Most Coveted Address",
    excerpt: "A guided tour of Nigeria's most exclusive residential enclave — its history, architecture, residents, and why a property here remains the ultimate status acquisition.",
    publishedAt: '2026-05-15T00:00:00Z',
    readTime: '7 min',
    author: 'Amara Obi',
    authorRole: 'Senior Property Advisor',
    authorBio: '12 years advising ultra-high-net-worth clients on luxury acquisitions across Lagos and Abuja.',
    featured: false,
    tags: ['Banana Island', 'Neighbourhoods', 'Lagos'],
    coverImageUrl: null,
    body: null,
  },
  {
    _id: '4',
    slug: 'shortlet-economy',
    category: 'living',
    title: 'The New Shortlet Economy: How Furnished Residences Are Reshaping Nigerian Hospitality',
    excerpt: 'Premium furnished apartments are redefining short-stay culture in Lagos and Abuja. We explore the rise of the luxury shortlet and its implications for buyers and investors.',
    publishedAt: '2026-05-10T00:00:00Z',
    readTime: '5 min',
    author: 'Amara Obi',
    authorRole: 'Senior Property Advisor',
    authorBio: '12 years advising ultra-high-net-worth clients on luxury acquisitions across Lagos and Abuja.',
    featured: false,
    tags: ['Shortlet', 'Lagos', 'Abuja'],
    coverImageUrl: null,
    body: null,
  },
  {
    _id: '5',
    slug: 'maitama-abuja',
    category: 'neighbourhood',
    title: 'Maitama, Abuja: Where Prestige, Privacy and Premium Returns Converge',
    excerpt: "The Federal Capital Territory's premier residential district has quietly become one of Nigeria's strongest property markets. A deep dive into what makes Maitama compelling.",
    publishedAt: '2026-05-03T00:00:00Z',
    readTime: '6 min',
    author: 'Amara Obi',
    authorRole: 'Senior Property Advisor',
    authorBio: '12 years advising ultra-high-net-worth clients on luxury acquisitions across Lagos and Abuja.',
    featured: false,
    tags: ['Maitama', 'Abuja', 'Investment'],
    coverImageUrl: null,
    body: null,
  },
  {
    _id: '6',
    slug: 'naira-valuations',
    category: 'market',
    title: 'Understanding Naira-Denominated Property Valuations in a Post-Float Era',
    excerpt: "The naira's liberalisation has created both complexity and opportunity in Nigeria's luxury property market. Here is what buyers, sellers, and investors need to understand.",
    publishedAt: '2026-04-26T00:00:00Z',
    readTime: '9 min',
    author: 'Amara Obi',
    authorRole: 'Senior Property Advisor',
    authorBio: '12 years advising ultra-high-net-worth clients on luxury acquisitions across Lagos and Abuja.',
    featured: false,
    tags: ['Naira', 'Valuations', 'Market Insights'],
    coverImageUrl: null,
    body: null,
  },
  {
    _id: '7',
    slug: 'private-estates',
    category: 'living',
    title: "Inside Nigeria's Most Exclusive Private Estates: Architecture, Community and Legacy",
    excerpt: 'A curated look at the gated communities that define ultra-premium residential living in Nigeria — the amenities, the architecture, and the communities they have cultivated.',
    publishedAt: '2026-04-18T00:00:00Z',
    readTime: '7 min',
    author: 'Amara Obi',
    authorRole: 'Senior Property Advisor',
    authorBio: '12 years advising ultra-high-net-worth clients on luxury acquisitions across Lagos and Abuja.',
    featured: false,
    tags: ['Private Estates', 'Lagos', 'Architecture'],
    coverImageUrl: null,
    body: null,
  },
];

export type Article = Omit<typeof STATIC_ARTICLES[0], 'body'> & { body?: unknown[] | null; authorImageUrl?: string | null };

export function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
}

export function authorInitial(name: string) {
  return name.charAt(0).toUpperCase();
}
